app/chatbot/models.py
from app.frase.models import obtener_frases_por_categoria, obtener_todas, frase_id
from datetime import datetime
import random

class ChatBot():
    def __init__(self):
        self.contexto = []

    def responder(self,frase):
        now = datetime.now()
        respuesta = ''
        categoria = ''
        dt_string = now.strftime("%H:%M")
        frases = obtener_todas()
        frase2 = frase
        frases2 = [frase['fra_v_frase'].lower() for frase in frases]
        for e in ['?','¿','!','¡',',']:
            frases2 = [frase.replace(e,'') for frase in frases2]
            frase2 = frase2.replace(e,'')
        for i in range(len(frases)):
            frases[i]['fra_v_frase'] = frases2[i]
        if frase2.lower() not in frases2:
            categoria = 'Default'
        else:
            for f in frases:
                if f['fra_v_frase'].lower() == frase2.lower():
                    categoria = f['fra_v_categoria']
        
    
        if categoria == 'Pregunta':
            respuestas = obtener_frases_por_categoria('Respuesta')
            respuesta = random.choice(respuestas)
            respuesta = respuesta['fra_v_frase']
        elif categoria == 'Pregunta-SN':
            respuestas = obtener_frases_por_categoria('Respuesta-SN')
            respuesta = random.choice(respuestas)
            respuesta = respuesta['fra_v_frase']
        elif categoria == 'Pregunta-lugar':
            respuestas = obtener_frases_por_categoria('Respuesta-lugar')
            respuesta = random.choice(respuestas)
            respuesta = respuesta['fra_v_frase']
        elif categoria == 'Pregunta-h':
            respuestas = obtener_frases_por_categoria('Respuesta-h')
            respuesta = random.choice(respuestas)
            respuesta = respuesta['fra_v_frase']
        else:
            respuestas = obtener_frases_por_categoria(categoria)
            respuesta = random.choice(respuestas)
            respuesta = respuesta['fra_v_frase']
        
        self.add_contexto({'user': frase, 'bot': respuesta, 'hora': dt_string})

    def add_contexto(self, ctx):
        self.contexto.append(ctx)

    

app/frase/models.py
from app.db import db, ma


class Frase(db.Model):
    fra_i_id = db.Column(db.Integer, primary_key=True)
    fra_v_frase = db.Column(db.String(45), nullable=False)
    fra_v_categoria = db.Column(db.String(45), nullable=False)

class FraseSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Frase
        fields = ["fra_i_id", "fra_v_frase", "fra_v_categoria"]

def obtener_frases_por_categoria(categoria):
    frases_filtro = Frase.query.filter_by(fra_v_categoria=categoria)
    if frases_filtro != None:
        frase_schema = FraseSchema()
        frases = [frase_schema.dump(f) for f in frases_filtro]
        return frases
    else:
        return None

def obtener_todas():
    frases = Frase.query.all()
    if frases != None:
        frase_schema = FraseSchema()
        frases = [frase_schema.dump(f) for f in frases]
        return frases
    else:
        return None




def crear_frase(frase, categoria):
    frase = Frase(fra_v_frase=frase, fra_v_categoria = categoria)
    db.session.add(frase)
    db.session.commit()
    frase_schema = FraseSchema()
    return frase_schema.dump(frase)

def frase_id(id):
    frase = Frase.query.filter_by(fra_i_id=id).first()
    if frase != None:
        frase_schema = FraseSchema()
        return frase_schema.dump(frase)
    else:
        return ''

def eliminar_frase(id):
    frase = Frase.query.filter_by(fra_i_id=id).first()
    if frase != None:
        Frase.query.filter_by(fra_i_id=id).delete()
        db.session.commit()
        return True
    else:
        return False

app/__init__.py
import os
from flask import Flask, redirect,url_for
from flask_migrate import Migrate
from conf.config import DevelpmentConfig
from app.db import db, ma
from app.frase.views import frase
from app.chatbot.views import chat


ADMINISTRADOR = [('/frase',frase),('/chat',chat)]

def create_app(config=DevelpmentConfig):
    app = Flask(__name__)
    migrate = Migrate(app, db)
    app.config.from_object(config)

    db.init_app(app)
    ma.init_app(app)
    migrate.init_app(app, db)


    with app.app_context():
        db.create_all()

    for url, blueprint in ADMINISTRADOR:
        app.register_blueprint(blueprint, url_prefix=url)

    
    return app

if __name__ == "__main__":
    app_flask = create_app()
    app_flask.run()

app/chatbot/views.py
from flask import Blueprint, render_template, url_for, redirect, request

from app.chatbot.models import ChatBot

chat = Blueprint("chat", __name__, url_prefix="/chat")
bot = ChatBot()

@chat.route("/", methods=["GET"])
def index():
    return render_template('chatbot/index.html')


@chat.route("/responder", methods=["POST"])
def responder():
    frase = request.form['frase']
    if frase.strip != '':
        bot.responder(frase)
        return render_template('chatbot/index.html',ctx = bot.contexto)
    else:
        return render_template('chatbot/index.html',ctx = bot.contexto)

app/frase/views.py
from http import HTTPStatus

from flask import Blueprint, render_template, url_for, redirect, request
import copy

from app.frase.models import crear_frase, eliminar_frase, obtener_todas

frase = Blueprint("frase", __name__, url_prefix="/frase")

RESPONSE_BODY_DEFAULT = {"message": "", "data": [], "errors": [], "metadata": []}


@frase.route("/", methods=["GET"])
def index():
    frases = obtener_todas()
    data = {
        "frases":frases
    }
    return render_template('frase/index.html', data=frases)


@frase.route("/agregar", methods=["POST","GET"])
def agregar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    if request.method == "POST":

        fra_v_frase = request.form["fra_v_frase"]
        fra_v_categoria = request.form["fra_v_categoria"]


        if fra_v_frase == "":
            response_body["errors"].append("Campo frase es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        if fra_v_categoria == "":
            response_body["errors"].append("Campo categoria es requerido")
            status_code = HTTPStatus.BAD_REQUEST
            return response_body, status_code

        frase = crear_frase(fra_v_frase, fra_v_categoria)

        return render_template('frase/agregar.html')
    else:

        return render_template('frase/agregar.html')


@frase.route("/eliminar/<int:id>", methods=["GET"])
def eliminar(id):
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.BAD_REQUEST
    if id != "":

        if eliminar_frase(id):
            return redirect(url_for('frase.index'))
        else:
            response_body["errors"].append("Error al eliminar la frase")
            return response_body, status_code

    else:
        response_body["errors"].append("El id es requerido, para eliminar la frase")
        return response_body, status_code

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}"/>
    <script src="{{ url_for('static', filename='js/script.js')}}"></script>
    <title>{% block title %}{% endblock %} - ChatBot</title>
    {% endblock %}
</head>
<body>
    <section class="content">{% block contenido %}{% endblock %}</section>
</body>
</html>

app/templates/chatbot/index.html
{% extends "base.html" %}
{% block title %} ChatBot {% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block contenido %}
<div class="page-content page-container" id="page-content">
  <div class="padding">
    <div class="row full-container d-flex justify-content-center">
      <div class="col-md-12">
        <div class="card card-bordered">
          <div class="card-header">
            <h4 class="card-title"><strong>Chat</strong></h4>
          </div>


          <div class="ps-container ps-theme-default ps-active-y" id="chat-content"
            style="overflow-y: scroll !important; height:400px !important;">

            {% for c in ctx %}
            <div class="media media-chat media-chat-reverse">
              <div class="media-body">
                <p>{{c.user}}</p>
                <p class="meta"><time datetime="2022">{{c.hora}}</time></p>
              </div>
            </div>

            <div class="media media-chat">
              <img class="avatar" src="https://img.icons8.com/color/36/000000/administrator-male.png" alt="...">
              <div class="media-body">
                <p>{{c.bot}}</p>
                <p class="meta"><time datetime="2022">{{c.hora}}</time></p>
              </div>
            </div>

            {% endfor %}

            <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
              <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
            </div>
            <div class="ps-scrollbar-y-rail" style="top: 0px; height: 0px; right: 2px;">
              <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 2px;"></div>
            </div>
          </div>

          <div class="publisher bt-1 border-light row full-container d-flex justify-content-center">
            <form method="post" style="width: 100%;" action="{{url_for('chat.responder')}}">
              <img class="avatar avatar-xs" src="https://img.icons8.com/color/36/000000/administrator-male.png"
                alt="...">
              <input name="frase" style="width: 90%" class="publisher-input" type="text" placeholder="Escribe algo">
              <button type="submit" class="publisher-btn text-info" data-abc="true"><i
                class="fa fa-paper-plane"></i></button>
            </form>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/frase/agregar.html
{% extends "frase_base.html" %}
{% block title %} Agregar Frase {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a id="1" class="nav-link" href="/frase">Lista de frases</a>
    </li>
    <li class="nav-item">
      <a id="2" class="nav-link active" href="/frase/agregar">Agregar frase</a>
    </li>
  </ul>
<div class="form-container">
    <form method="post" action="{{url_for('frase.agregar')}}">
        <div class="form-group">
          <label for="frase">Frase</label>
          <input name="fra_v_frase" type="text" class="form-control" id="frase"  placeholder="Frase">
        </div>
        <div class="form-group">
          <label for="cat">Categoria</label>
          <input name="fra_v_categoria" type="text" class="form-control" id="cat" placeholder="Categoria">
        </div>
    
        <button type="submit" class="btn btn-primary">Crear</button>
    </form>

</div>

{% endblock %}

app/templates/frase/index.html
{% extends "frase_base.html" %}
{% block title %} Frase {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block contenido %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a id="1" class="nav-link active" href="/frase">Lista de frases</a>
  </li>
  <li class="nav-item">
    <a id="2" class="nav-link" href="/frase/agregar">Agregar frase</a>
  </li>
</ul>
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Frase</th>
        <th scope="col">Categoria</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
      {% for frase in data %}
      <tr>
        <td>{{frase.fra_i_id}}</td>
        <td>{{frase.fra_v_frase}}</td>
        <td>{{frase.fra_v_categoria}}</td>
        <td><a class="btn btn-primary" href="{{url_for('frase.eliminar', id=frase.fra_i_id)}}" role="button">Eliminar</a></td>
      </tr>
     {% endfor %}
    </tbody>
  </table>
{% endblock %}

app/templates/frase_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style2.css')}}"/>
    <title>{% block title %}{% endblock %} - ChatBot</title>
    {% endblock %}
</head>
<body>
    
    <section class="content">{% block contenido %}{% endblock %}</section>
</body>
</html>